#!/usr/bin/python
# expects an input file to fetch tags from, and an output file to write the tags to.

import sys
from mutagen.id3 import ID3
from mutagen.easyid3 import EasyID3
from mutagen.flac import FLAC
from mutagen.mp3 import MP3

dest_id3 = ID3(sys.argv[2])
dest_id3.delete()

dest = MP3(sys.argv[2])
dest.add_tags(ID3=EasyID3)

source = FLAC(sys.argv[1])
#id3 = EasyID3(sys.argv[1])

dest.delete()

for key,value in source.items():
  print key, value
  if key == "album" or key == "artist" or key == "title" or key == "album\ artist" or key == "genre" or key == "date" or key == "tracknumber" or key == "discnumber":
    dest[key] = value

source.items

for key,value in dest.items():
  print key, value

dest.save()
