#!/bin/bash
rsync -av --size-only --delete --exclude="Automatically Add to iTunes.localized" --exclude="*.pamp" --exclude=".AppleDouble" --exclude="Unknown Artist" ${HOME}/Music/* /Volumes/PHONE-SD/MUSIC/
